---
- name: check bitcoind executable is present in PATH
  ansible.builtin.command: which bitcoind
  register: bitcoind_exists
  changed_when: bitcoind_exists.rc != 0
  ignore_errors: true

- name: bitcoind install required dependencies
  ansible.builtin.package:
    name: "{{ bitcoind_deps.debian }}"
    state: present
  when: bitcoind_exists.rc != 0

- name: bitcoind git checkout
  ansible.builtin.git:
    repo: https://github.com/bitcoin/bitcoin.git
    dest: "{{ bitcoind_src_dir }}"
    version: "{{ bitcoin_git_branch }}"
  when: bitcoind_exists.rc != 0

- name: bitcoind make depends
  ansible.builtin.command: make {{ bitcoind_make_depends_params }}
  args:
    chdir: "{{ bitcoind_src_dir }}/depends"
  when: bitcoind_exists.rc != 0

- name: bitcoind autogen
  ansible.builtin.command: ./autogen.sh
  args:
    chdir: "{{ bitcoind_src_dir }}"
  when: bitcoind_exists.rc != 0

- name: bitcoind configure
  ansible.builtin.command: ./configure {{ bitcoind_configure_options }}
  args:
    chdir: "{{ bitcoind_src_dir }}"
  environment:
    CONFIG_SITE: "{{ bitcoind_config_site }}"
  when: bitcoind_exists.rc != 0

- name: bitcoind compile
  ansible.builtin.command: make {{ bitcoind_make_params }}
  args:
    chdir: "{{ bitcoind_src_dir }}"
  when: bitcoind_exists.rc != 0

- name: bitcoind install
  ansible.builtin.command: make install
  args:
    chdir: "{{ bitcoind_src_dir }}"
  when: bitcoind_exists.rc != 0
